name: Droidspaces

on:
  workflow_dispatch:
  schedule:
    - cron: '5 1 * * 0'

permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest
    outputs:
      timestamp: ${{ steps.ts.outputs.TIME }}
      date: ${{ steps.ts.outputs.DATE }}
    strategy:
      matrix:
        build-type: [sweet-droidspaces, ginkgo-droidspaces, umi-droidspaces, mi89x7-droidspaces]
        ksu-type: [zako, zako-susfs, none]
        bbg-type: [bbg]
        nomount-type: [nomount]
        droidspaces-type: [droidspaces]
        rekernel-type: [rekernel]

    steps:
      - uses: actions/checkout@v6

      - name: Timestamp
        id: ts
        run: |
          DATE=$(date +'%Y%m%d')
          TIME=$(date +'%s')
          echo "DATE=$DATE" >> $GITHUB_OUTPUT
          echo "TIME=$TIME" >> $GITHUB_OUTPUT

      - name: Install build dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y \
            bc build-essential bison flex zip p7zip-full \
            libc6 curl libstdc++6 git wget libssl-dev zstd \
            lld python3 patchutils ccache

      - name: Preparing kernel sources
        run: |
          if [[ "${{ matrix.build-type }}" == "sweet-droidspaces" ]]; then
            if [ -d "$PWD/android_kernel_xiaomi_sm6150" ]; then
              rm -rf android_kernel_xiaomi_sm6150
            fi
            echo "Cloning kernel sources..."
            git clone https://github.com/LineageOS/android_kernel_xiaomi_sm6150.git -b "lineage-23.2" --depth=1 android_kernel_xiaomi_sm6150
            echo "Copying buildscript..."
            cp build.sh android_kernel_xiaomi_sm6150/
            cp -r scripts android_kernel_xiaomi_sm6150/
            chmod +x ./android_kernel_xiaomi_sm6150/build.sh
          elif [[ "${{ matrix.build-type }}" == "ginkgo-droidspaces" ]]; then
            if [ -d "$PWD/android_kernel_xiaomi_sm6125" ]; then
              rm -rf android_kernel_xiaomi_sm6125
            fi
            echo "Cloning kernel sources..."
            git clone https://github.com/LineageOS/android_kernel_xiaomi_sm6125.git -b "lineage-23.2" --depth=1 android_kernel_xiaomi_sm6125
            echo "Copying buildscript..."
            cp build.sh android_kernel_xiaomi_sm6125/
            cp -r scripts android_kernel_xiaomi_sm6125/
            chmod +x ./android_kernel_xiaomi_sm6125/build.sh
          elif [[ "${{ matrix.build-type }}" == "umi-droidspaces" ]]; then
            if [ -d "$PWD/android_kernel_xiaomi_sm8250" ]; then
              rm -rf android_kernel_xiaomi_sm8250
            fi
            echo "Cloning kernel sources..."
            git clone https://github.com/LineageOS/android_kernel_xiaomi_sm8250.git -b "lineage-23.2" --depth=1 android_kernel_xiaomi_sm8250
            echo "Copying buildscript..."
            cp build.sh android_kernel_xiaomi_sm8250/
            cp -r scripts android_kernel_xiaomi_sm8250/
            chmod +x ./android_kernel_xiaomi_sm8250/build.sh
          elif [[ "${{ matrix.build-type }}" == "mi89x7-droidspaces" ]]; then
            if [ -d "$PWD/android_kernel_xiaomi_msm8937" ]; then
              rm -rf android_kernel_xiaomi_msm8937
            fi
            echo "Cloning kernel sources..."
            # Main source
            git clone https://github.com/Mi-Thorium/kernel_msm-4.19 --depth=1 -b "mithorium/a13/master" android_kernel_xiaomi_msm8937
            # Dts vendor-legacy
            git clone https://github.com/Mi-Thorium/kernel_devicetree_msm-4.19 --depth=1 -b "dts/master" android_kernel_xiaomi_msm8937/arch/arm64/boot/dts/vendor-legacy
            # Dts msm8937
            git clone https://github.com/Mi-Thorium/kernel_devicetree_xiaomi-msm8937 --depth=1 -b "dts/mi8937/4.19/master" android_kernel_xiaomi_msm8937/arch/arm64/boot/dts/xiaomi-msm8937
            # Dts sdm439
            git clone https://github.com/Mi-Thorium/kernel_devicetree_xiaomi-sdm439 --depth=1 -b "dts/mi439/4.19/master" android_kernel_xiaomi_msm8937/arch/arm64/boot/dts/xiaomi-sdm439
            # Techpack msm8937
            git clone https://github.com/Mi-Thorium/kernel_techpack_xiaomi-msm8937 --depth=1 -b "techpack/mi8937/4.19/master" android_kernel_xiaomi_msm8937/techpack/xiaomi-msm8937
            # Techpack sdm439
            git clone https://github.com/Mi-Thorium/kernel_techpack_xiaomi-sdm439 --depth=1 -b "techpack/mi439/4.19/master" android_kernel_xiaomi_msm8937/techpack/xiaomi-sdm439
            # Techpack audio-legacy
            git clone https://github.com/Mi-Thorium/kernel_techpack_audio-legacy --depth=1 -b "audio/4.19/mithorium/master" android_kernel_xiaomi_msm8937/techpack/audio-legacy
            # Techpack camera-legacy
            git clone https://github.com/Mi-Thorium/kernel_techpack_camera-legacy --depth=1 -b "camera/LA.UM.8.6.r1-05300-89xx.0/4.19/mithorium" android_kernel_xiaomi_msm8937/techpack/camera-legacy
            # Techpack camera-legacy-m
            git clone https://github.com/Mi-Thorium/kernel_techpack_camera-legacy --depth=1 -b "camera/LA.UM.5.3-10610-89xx.0/4.19/mithorium" android_kernel_xiaomi_msm8937/techpack/camera-legacy-m
            # Prima WIFI
            git clone https://github.com/Mi-Thorium/vendor_qcom_opensource_wlan_prima --depth=1 -b "wlan/LA.UM.9.6.4/mithorium/master" android_kernel_xiaomi_msm8937/drivers/staging/prima
            # Final
            echo "Copying buildscript..."
            cp build.sh android_kernel_xiaomi_msm8937/
            cp -r scripts android_kernel_xiaomi_msm8937/
            chmod +x ./android_kernel_xiaomi_msm8937/build.sh
          else
            echo "Invalid build type: ${{ matrix.build-type }}"
            exit 1
          fi

      - name: Compile the kernel
        run: |
          echo "Starting to compile..."
          if [[ "${{ matrix.build-type }}" == "sweet-droidspaces" ]]; then
            cd android_kernel_xiaomi_sm6150/
            ./build.sh ${{ matrix.build-type }} ${{ matrix.ksu-type }} ${{ matrix.bbg-type }} ${{ matrix.nomount-type }} ${{ matrix.droidspaces-type }} ${{ matrix.rekernel-type }}
            cd ..
          elif [[ "${{ matrix.build-type }}" == "ginkgo-droidspaces" ]]; then
            cd android_kernel_xiaomi_sm6125/
            ./build.sh ${{ matrix.build-type }} ${{ matrix.ksu-type }} ${{ matrix.bbg-type }} ${{ matrix.nomount-type }} ${{ matrix.droidspaces-type }} ${{ matrix.rekernel-type }}
            cd ..
          elif [[ "${{ matrix.build-type }}" == "umi-droidspaces" ]]; then
            cd android_kernel_xiaomi_sm8250/
            ./build.sh ${{ matrix.build-type }} ${{ matrix.ksu-type }} ${{ matrix.bbg-type }} ${{ matrix.nomount-type }} ${{ matrix.droidspaces-type }} ${{ matrix.rekernel-type }}
            cd ..
          elif [[ "${{ matrix.build-type }}" == "mi89x7-droidspaces" ]]; then
            cd android_kernel_xiaomi_msm8937/
            ./build.sh ${{ matrix.build-type }} ${{ matrix.ksu-type }} ${{ matrix.bbg-type }} ${{ matrix.nomount-type }} ${{ matrix.droidspaces-type }} ${{ matrix.rekernel-type }}
            cd ..
          else
            echo "Invalid build type: ${{ matrix.build-type }}"
            exit 1
          fi

      - name: Preparing AnyKernel3 sources
        run: |
          if [ -d "$PWD/AnyKernel3" ]; then
            rm -rf AnyKernel3
          fi
          git clone https://github.com/riarumoda/AnyKernel3 AnyKernel3 --depth=1
          if [[ "${{ matrix.build-type }}" == "sweet-droidspaces" ]]; then
            cp android_kernel_xiaomi_sm6150/out/arch/arm64/boot/Image.gz AnyKernel3/
            cp android_kernel_xiaomi_sm6150/out/arch/arm64/boot/dtb.img AnyKernel3/
            cp android_kernel_xiaomi_sm6150/out/arch/arm64/boot/dtbo.img AnyKernel3/
            sed -i 's/supported.versions=11-16/supported.versions=11-16/' AnyKernel3/anykernel.sh
            if [[ "${{ matrix.build-type }}" == "sweet-droidspaces" ]]; then
              sed -i 's/device.name1=sweet/device.name1=sweet/' AnyKernel3/anykernel.sh
              sed -i 's/device.name2=sweetin/device.name2=sweetin/' AnyKernel3/anykernel.sh
              sed -i 's/sweet (sm6150)/sweet (sm6150)/g' AnyKernel3/banner
            fi
          elif [[ "${{ matrix.build-type }}" == "ginkgo-droidspaces" ]]; then
            cp android_kernel_xiaomi_sm6125/out/arch/arm64/boot/Image.gz AnyKernel3/
            cp android_kernel_xiaomi_sm6125/out/arch/arm64/boot/dtb.img AnyKernel3/
            cp android_kernel_xiaomi_sm6125/out/arch/arm64/boot/dtbo.img AnyKernel3/
            sed -i 's/supported.versions=11-16/supported.versions=11-16/' AnyKernel3/anykernel.sh
            if [[ "${{ matrix.build-type }}" == "ginkgo-droidspaces" ]]; then
              sed -i 's/device.name1=sweet/device.name1=ginkgo/' AnyKernel3/anykernel.sh
              sed -i 's/device.name2=sweetin/device.name2=willow/' AnyKernel3/anykernel.sh
              sed -i 's/sweet (sm6150)/ginkgo (sm6125)/g' AnyKernel3/banner
            fi
          elif [[ "${{ matrix.build-type }}" == "umi-droidspaces" ]]; then
            cp android_kernel_xiaomi_sm8250/out/arch/arm64/boot/Image AnyKernel3/
            sed -i 's/supported.versions=11-16/supported.versions=11-16/' AnyKernel3/anykernel.sh
            if [[ "${{ matrix.build-type }}" == "umi-droidspaces" ]]; then
              sed -i 's/device.name1=sweet/device.name1=umi/' AnyKernel3/anykernel.sh
              sed -i 's/device.name2=sweetin/device.name2=umiin/' AnyKernel3/anykernel.sh
              sed -i 's/sweet (sm6150)/umi (sm8250)/g' AnyKernel3/banner
            fi
          elif [[ "${{ matrix.build-type }}" == "mi89x7-droidspaces" ]]; then
            cp android_kernel_xiaomi_msm8937/out/arch/arm64/boot/Image.gz-dtb AnyKernel3/
            sed -i 's/supported.versions=11-16/supported.versions=11-16/' AnyKernel3/anykernel.sh
            sed -i 's/device.name1=sweet/device.name1=mi8937/' AnyKernel3/anykernel.sh
            sed -i 's/device.name2=sweetin/device.name2=mi8917/' AnyKernel3/anykernel.sh
            sed -i '/device.name2=mi8917/a device.name3=santoni\ndevice.name4=prada\ndevice.name5=rolex\ndevice.name6=ugglite\ndevice.name7=riva\ndevice.name8=ugg' AnyKernel3/anykernel.sh
            sed -i 's/sweet (sm6150)/mi8937 and mi8917 (msm8937)/g' AnyKernel3/banner
          else
            echo "Invalid build type: ${{ matrix.build-type }}"
            exit 1
          fi
          sed -i '$a \\nBuild timestamp: ${{ steps.ts.outputs.TIME }}' AnyKernel3/banner

      - name: Pack kernel with AnyKernel3
        run: |
          if [[ "${{ matrix.ksu-type }}" == "zako" ]]; then
            export KSUTYPE="normal"
          elif [[ "${{ matrix.ksu-type }}" == "zako-susfs" ]]; then
            export KSUTYPE="susfs"
          elif [[ "${{ matrix.ksu-type }}" == "none" ]]; then
            export KSUTYPE="noksu"
          fi
          if [[ "${{ matrix.build-type }}" == "mi89x7-droidspaces" ]]; then
            export KERNELNAME="Mi8937v2"
          else
            export KERNELNAME="perf-neon"
          fi
          ZIPNAME="$KERNELNAME-${{ matrix.build-type }}-$KSUTYPE-${{ steps.ts.outputs.DATE }}.zip"
          cd AnyKernel3
          zip -rq9 "../$ZIPNAME" ./*
          cd ..

      - name: Upload artifacts (All builds)
        uses: actions/upload-artifact@v6
        with:
          name: ${{ matrix.build-type }}-${{ matrix.ksu-type }}
          path: |
            *.zip

  release:
    needs: build
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
      - name: Download all build artifacts
        uses: actions/download-artifact@v4
        with:
          path: ./artifacts

      - name: List downloaded zips
        run: ls -lah artifacts

      - name: Timestamp
        id: ts
        run: |
          FANCYDATE=$(date +'%Y/%m/%d')
          echo "FANCYDATE=$FANCYDATE" >> $GITHUB_OUTPUT

      - name: Create Release and Upload builds
        uses: softprops/action-gh-release@v2
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: kernel-droidspaces-${{ needs.build.outputs.timestamp }}
          name: Droidspaces - ${{ steps.ts.outputs.FANCYDATE }}
          draft: false
          prerelease: true
          body: |
            > [!IMPORTANT]
            > - This kernel build have been split from the main weekly releases due to side effects of how Droidspaces being implemented.   
            > - This build already include the things you expect from the main releases.

            > [!CAUTION]   
            > - Always backup your boot & dtbo image first before proceeding!   
          files: |
            artifacts/**/*.zip
          overwrite_files: true
